### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by nsheff** [databio/lucidoc#17]
try to autodoc pypiper I can't understand what it's saying here:

```
    raise lucidocError("Invalid tag declaration start: " + line)
lucidoc.exceptions.lucidocError: Invalid tag declaration start: :type config_file: str
```
The line in question is ":type config_file: str", but this seems to be the same way we are documenting types in divvy, so why is it not working here?

**Comment by nsheff** [comment]
but here's an example of what seems to be the problematic using in `divvy`, which can be processed by lucidoc:

https://github.com/pepkit/divvy/blob/b9083ac663abcc7509046fa2f928e1b0d072aff1/divvy/utils.py#L435

**Comment by vreuter** [comment]
> Is this the correct syntax change to make?
> 
> [databio/pypiper@456f1b5](https://github.com/databio/pypiper/commit/456f1b5a3d6f78682b22aa780e6996270918d766)

Indeed!

**Comment by vreuter** [comment]
> but here's an example of what seems to be the problematic using in `divvy`, which can be processed by lucidoc:
> 
> https://github.com/pepkit/divvy/blob/b9083ac663abcc7509046fa2f928e1b0d072aff1/divvy/utils.py#L435

`CommandChecker` isn't exported (https://github.com/pepkit/divvy/blob/dev/divvy/__init__.py#L19), so no attempt is made to process its docstring

**Comment by nsheff** [comment]
> CommandChecker isn't exported (https://github.com/pepkit/divvy/blob/dev/divvy/__init__.py#L19), so no attempt is made to process its docstring

I thought that might be the case. I guess we will need to address those docstrings too though at some point

**Comment by nsheff** [comment]
thanks.
