### ISSUE TITLE
Include version numbers in output

### ISSUE THREAD

**Issue by nsheff** [databio/lucidoc#25]
maybe at the bottom of any rendered markdown page we should include:

- the version of the package being documented
- the version of lucidoc used to document it 

eg:

Documentation of package `pkgname v0.10.0` generated by [lucidoc v0.2](http://link/to/lucidoc).

Could be suppressed with a command line arg? This would make it easier to 1) make sure we're documenting the correct package version; and 2) advertise lucidoc a bit.

**Comment by vreuter** [comment]
Yeah good idea
