### ISSUE TITLE
Understanding the --whitelist argument

### ISSUE THREAD

**Issue by nsheff** [databio/lucidoc#26]
Based on the documentation, I was expecting this to document just one class:

```
lucidoc pypiper -P rst --whitelist PipelineManager
```

but it outputs a blank document:

```
# Package pypiper Documentation
```

what am I doing incorrectly? I was able to get it to work as expected with the `output-groups` option by saying `pm=PipelineManager`, but does the `whitelist` option have a different api?

**Comment by vreuter** [comment]
Sorry, it shouldn’t be available. Meant to drop it and blacklist from released version since they’re untested but forgot to remove them

**Comment by vreuter** [comment]
You’re using it exactly as intended, Injust meant to remove it since it’s totally untested

**Comment by vreuter** [comment]
This should be functional in the 0.3 release.

**Comment by nsheff** [comment]
wait, so you ended up keeping them instead of dropping them as originally suggested? Great! I personally liked the whitelist/blacklist interface

**Comment by vreuter** [comment]
Yeah sorry for the confusion; I meant that I'd intended to drop them prior to last release, but not necessarily permanently. I think `--whitelist` is still a nice convenience albeit less powered than the groups way, and `--blacklist` provides something only previously achievable in the complementary way.
