### ISSUE TITLE
Selection of which methods to document appears incorrect.

### ISSUE THREAD

**Issue by nsheff** [databio/lucidoc#27]
When I document `pypiper` using the latest version of lucidoc, I get this: 

```
 lucidoc pypiper -P rst --output-groups pm=PipelineManager
Groups provided; only declared group members will be used in documentation
Processing class: PipelineManager
Processing function: completed
Processing function: failed
Processing function: halted
Processing function: has_exit_status
Processing function: is_running
Base output folder: /home/sheffien/code/pypiper
Writing docs: /home/sheffien/code/pypiper/pm.md
Done.
```
Which yields this result:
```
sheffien@nox:~/code/pypiper$ cat /home/sheffien/code/pypiper/pm.md
```

# Package pypiper Documentation

## Class PipelineManager
Base class for instantiating a PipelineManager object, the main class of Pypiper.

**Parameters:**

- `name` -- `str`:  Choose a name for your pipeline;it's used to name the output files, flags, etc.
- `outfolder` -- `str`:  Folder in which to store the results.
- `args` -- `argparse.Namespace`:  Optional args object from ArgumentParser;Pypiper will simply record these arguments from your script
- `multi` -- `bool`:  Enables running multiple pipelines in one scriptor for interactive use. It simply disables the tee of the output, so you won't get output logged to a file.
- `dirty` -- `bool`:  Overrides the pipeline's clean_add()manual parameters, to *never* clean up intermediate files automatically. Useful for debugging; all cleanup files are added to manual cleanup script.
- `recover` -- `bool`:  Specify recover mode, to overwrite lock files.If pypiper encounters a locked target, it will ignore the lock and recompute this step. Useful to restart a failed pipeline.
- `new_start` -- `bool`:  start over and run every command even if output exists
- `force_follow` -- `bool`:  Force run all follow functionseven if  the preceding command is not run. By default, following functions  are only run if the preceding command is run.
- `cores` -- `int`:  number of processors to use, default 1
- `mem` -- `str`:  amount of memory to use, in Mb
- `config_file` -- `str`:  path to pipeline configuration file, optional
- `output_parent` -- `str`:  path to folder in which output folder will live
- `overwrite_checkpoints` -- `bool`:  Whether to override the stage-skippinglogic provided by the checkpointing system. This is useful if the calls to this manager's run() method will be coming from a class that implements pypiper.Pipeline, as such a class will handle checkpointing logic automatically, and will set this to True to protect from a case in which a restart begins upstream of a stage for which a checkpoint file already exists, but that depends on the upstream stage and thus should be rerun if it's "parent" is rerun.

**Raises:**

- `TypeError`:  if start or stop point(s) are provided both directly andvia args namespace, or if both stopping types (exclusive/prospective and inclusive/retrospective) are provided.

### completed
Is the managed pipeline in a completed state?
```python
def completed(self)
```

**Returns:**

`bool`:  Whether the managed pipeline is in a completed state.

### failed
Is the managed pipeline in a failed state?
```python
def failed(self)
```

**Returns:**

`bool`:  Whether the managed pipeline is in a failed state.

### halted
Is the managed pipeline in a paused/halted state?
```python
def halted(self)
```

**Returns:**

`bool`:  Whether the managed pipeline is in a paused/halted state.

### has\_exit\_status
Has the managed pipeline been safely stopped?
```python
def has_exit_status(self)
```

**Returns:**

`bool`:  Whether the managed pipeline's status indicates that ithas been safely stopped.

### is\_running
Is the managed pipeline running?
```python
def is_running(self)
```

**Returns:**

`bool`:  Whether the managed pipeline is running.

---

I know we have `lucidoc` no longer documenting private members, which is great -- and we made a bunch of pypiper methods private, so they aren't showing up anymore... but there are now public methods that are not showing up anymore; for example, why is `start_pipeline()` not rendered any longer?

https://github.com/databio/pypiper/blob/653216887cb2b2ad8e9119b76f40b39da58ec115/pypiper/manager.py#L376

**Comment by vreuter** [comment]
Do you no longer plan to use whatever Sphinx offers for markdown rendering? If that will be adopted, I don’t think it makes sense to do anything with this project.

**Comment by nsheff** [comment]
well, we can look into it again. This is the link I'll need to look at in detail: https://stackoverflow.com/questions/2471804/using-sphinx-with-markdown-instead-of-rst

**Comment by nsheff** [comment]
There's no existing solution that does exactly what we need; the existing things basically allow you to use markdown instead of rst with sphinx. I'd rather use mkdocs...

Here's the `autodoc` extension code from sphinx that actually does the parsing of rst docstrings: 

https://bitbucket.org/birkenfeld/sphinx/src/122bbbbd002e0b1c66145d81097b7a69c216e917/sphinx/ext/autodoc.py?at=default&fileviewer=file-view-default

And `napolean` converts google-style and numpy-style docstrings into rst style: 

https://bitbucket.org/birkenfeld/sphinx/src/122bbbbd002e0b1c66145d81097b7a69c216e917/sphinx/ext/napoleon/docstring.py?at=default&fileviewer=file-view-default

I'm digging into this a bit deeper...

**Comment by nsheff** [comment]
Alright, after looking into this for a few hours, I've been unable to identify anything that exists that does *everything* we're trying to accomplish, but I did find something...

We can use `napolean` to convert all docstrings into `rst`. This works well: 

```
from sphinx.ext.napoleon import Config
from sphinx.ext.napoleon import GoogleDocstring

config = Config(napoleon_use_param=True, napoleon_use_rtype=True)
docstring = '''One line summary.
Extended description.
Args:
  arg1(int): Description of `arg1`
  arg2(str): Description of `arg2`
Returns:
  str: Description of return value.
'''

gd = GoogleDocstring(docstring, config)

print(gd)

```

Ideally, we could use `napolean` to convert all docstrings to rst, and then use the basic `sphinx.autodoc` functionality to parse the rst docstrings, and then write our own outputter to take that and output markdown. However, I have been unable to dissect how sphinx is actually parsing the rst docstrings to create documentation.... going down this route:

```
import pypiper
from sphinx.ext.autodoc import ModuleDocumenter

md = ModuleDocumenter(Highlight(), name="pypiper")
```

just gives errors. It seems to me the autodocumenter is really tightly intertwined with the sphinx system and I cannot figure out how to make use of it. It is too large and complex.

So I'm attempting to understand `lucidoc` so I can solve the above problem...

```
import lucidoc
from lucidoc import RstDocstringParser
rdp = RstDocstringParser()

## How to actually document this?

lucidoc.doc_class(pypiper.PipelineManager, rdp, render_tag=lucidoc.DocTag, include_inherited=False)
lucidoc.doc_module(pypiper, rdp, render_tag=lucidoc.DocTag, include_inherited=False)

```
This yields:

```
TypeError: __init__() missing 1 required positional argument: 'description'
```

`lucidoc` has many layers of anonymous functions and function calls and I can't trace the logic through here... what are DocTags and why are they needed? And how do I pass them along? I was eventually able to slap together some code that I got to run:

```
show_tag = lucidoc.MdTagRenderer()
doc_res = lucidoc.doc_module(pypiper, rdp, show_tag)
lucidoc.doc_module(pypiper, rdp, render_tag=lucidoc.DocTag, include_inherited=False)
```

Which yields: 

```
Processing class: AttMapEcho
Processing class: IllegalPipelineDefinitionError
Processing class: IllegalPipelineExecutionError
Processing class: MissingCheckpointError
Processing class: NGSTk
Processing function: ziptool
Processing class: Pipeline
Processing function: outfolder
Processing function: stage_names
Processing class: PipelineError
Processing class: PipelineHalt
Processing class: PipelineManager
Processing function: halted
Processing class: Stage
Processing function: checkpoint_name
Processing class: SubprocessError
Processing class: UnknownPipelineStageError
Processing class: UnsupportedFiletypeException
Processing function: add_pypiper_args
Processing function: build_command
Processing function: get_first_value
Processing function: is_fastq
Processing function: is_gzipped_fastq
Processing function: is_sam_or_bam
```

This returned the docs, which I can view with `print(doc_res)`, which is nice. I was then able to get the class documenter (which I assume is called by the module documenter) to work like this: 

```
doc_res = lucidoc.doc_class(pypiper.PipelineManager, rdp, show_tag, include_inherited=False)
```

But this is not correctly documenting all the members of the object. As near I can tell there's an error somewhere in here: 

https://github.com/databio/lucidoc/blob/9ca0654d35d2c190825981a43d901e72bbc8fa23/lucidoc/lucidoc.py#L303-L310

but I'm really having trouble understanding the logic here because there's a lot of abstractions. For example, what is `proc` and what is a `subobject` here? 

https://github.com/databio/lucidoc/blob/9ca0654d35d2c190825981a43d901e72bbc8fa23/lucidoc/lucidoc.py#L418-L419

I feel like I'm close but just struggling to understand the inner workings of lucidoc...


My conclusion of all this is that I think lucidoc is probably a worthwhile project
. Take a look for example at this recent reddit thread: https://news.ycombinator.com/item?id=17716791

I still agree with you that we shouldn't invest too much more in it right now, but it would be nice if we could at least patch the few remaining bugs so that we can use it to autodocument stuff -- it was working *almost* perfectly before, and I feel like we're very close to something that will be very useful, even if it's not totally perfect/flexible... what do you think?

**Comment by vreuter** [comment]
Behavior differs between python 2 and 3. In 2 behavior appears correct; in 3 the function-wise processing short-circuits, halting before everything's been processed.

**Comment by nsheff** [comment]
Ah!! That's what happened! I was so confused because it seemed to be working... thanks for figuring that out :clap:

**Comment by vreuter** [comment]
Sure no problem; I still need to be solve this for 3, but at least in the meantime they can be rendered if needed with 2

**Comment by nsheff** [comment]
Yeah, that's perfect. I feel like an idiot as well :man_facepalming: I spent several hours trying to figure this out

**Comment by vreuter** [comment]
> Yeah, that's perfect. I feel like an idiot as well man_facepalming I spent several hours trying to figure this out

Yeah although the compatibility stuff is a little thorny now it'll be nice to be transitioned to just one major version in the not-too-distant future.

**Comment by nsheff** [comment]
:candy: 

I can confirm that works, nice!
