### ISSUE TITLE
remove bold on 'Returns' and 'Parameters'

### ISSUE THREAD

**Issue by nsheff** [databio/lucidoc#30]
I can't easily  find where the actual markdown is being generated so I can tweak the way it's output, can you point me to where that is?

I'd like to make "Returns" and "Parameters" *not* bold... it makes them stand out more than the header levels above them, so it's hard to put together chunks of information.

For example:  http://attmap.databio.org/en/latest/autodoc_build/attmap/

is this coming from lucidoc?

**Comment by vreuter** [comment]
OK the change looks effective when I serve `attmap` API docs locally. Can you confirm?

**Comment by vreuter** [comment]
After pulling `dev` and reinstalling, that is. New release time?

**Comment by nsheff** [comment]
I'll give it a try, then yes!

**Comment by nsheff** [comment]
alright I rendered it and I like just switching to italics.

But in the process I had another suggestion which is harder for me to dig in to:

Right now you're showing the function names as level 3 headers, like:  '### {}' 
and then after showing the docstring for the function, you show the function signature as code.

This is repeating the function name in the header, and then in the code definition. Can we merge these into just showing the function signature? I don't see why you want a header separate from the signature. I'd just put the signature in the header.

**Comment by vreuter** [comment]
It's that way for 2 reasons, but open to change:
1. (Arguably) greater visual clutter -- adding parameters to the header will fill more whitespace. Total text would be reduced, but the the amount of text at header size will be greater in both absolute and--even more so--in relative terms.
2. Can code be rendered in header? I like having the signatures be more code-like, but that's not a strong preference.

**Comment by nsheff** [comment]
well... you *can* render code in the header... but yeah it looks different. maybe this should just not be a header then? I agree that the functions should be code-like.

I don't know the solution but the current way is hard for me to parse visually. I think in absence of something better we should mimic the way readthedocs does it.

for example:

https://pybpod-api.readthedocs.io/en/v1.6.3/api_reference/pybpodapi/state_machine/state_machine.html

here each function is shown once, as code, in a header-like entity. how close can we get to this in pure markdown? to really get at how they do it will likely require some dedicated css styles in addition, but I think the first step is to merge the 2 places we're putting the function names

# New idea:

I've just added a branch where I have come up with something I think looks good. It adds some script to the top... not sure the best way to do this. The only thing that needs to change is that the complete signature move up into the header instead of the way it is duplicated now. I couldn't easily figure out how to do that.

can you give that a look and see what you think?

**Comment by vreuter** [comment]
Yeah it looks good save for the lingering headers; are you good with the rendition once those are removed?

![lucidoc_headerse](https://user-images.githubusercontent.com/12036370/57889974-47201d00-7804-11e9-91fc-0e06d6b3a916.png)
