### ISSUE TITLE
refgenconf docs render strangely

### ISSUE THREAD

**Issue by nsheff** [databio/lucidoc#43]
see: http://refgenie.databio.org/en/latest/autodoc_build/refgenconf/

in 'order' parameter always looks weird:

```
Parameters:
genome (str | NoneType): reference genome assembly ID, optional;if omitted, the full mapping from genome to asset names
order (``): function(str) -> object how to key genome IDs and assetnames for sort
include_tags (bool): whether asset tags should be included in the returned dict
```

The style of ` :param order: function(str) -> object ` in the docstring is not being parsed correctly.

**Comment by stolarczyk** [comment]
`:param order: function(str) -> object` that's incorrect format. 

It should read:`:param function(str) -> object  order:`
