### ISSUE TITLE
Supported python versions

### ISSUE THREAD

**Issue by vreuter** [databio/lucidoc#48]
The `setup.py`, and it looks like the test matrix for Travis, are upper bounded at Python 3.6. Could this be lifted and tests run / support advertised for versions of Python beyond 3.6, or is there something here that limits the supported version?

**Comment by nsheff** [comment]
No, there is nothing. It's just that nobody has looked at this for a couple of years and so we haven't updated these things.

**Comment by nsheff** [comment]
In other words, we should definitely update, and probably move away from travis and use github actions instead, anyway. I can set this up following the patterns we'ev used in other packages.

**Comment by nsheff** [comment]
Fixed in release 0.4.4
